configs:

  - ip: 224.10.10.10
    ciphersuite: blowfish/ECB/PKCS5Padding
    provider: BC
    keySize: 256
    keyValue: null
    macKm: HMacSHA1
    macKmKeySize: 256
    macKmKeyValue: null
    macKa: HMacSHA1
    macKaKeySize: 256
    macKaKeyValue: null

  - ip: 238.69.69.69
    ciphersuite: blowfish/ECB/PKCS5Padding
    provider: BC
    keySize: 256
    keyValue: null
    macKm: HMacSHA1
    macKmKeySize: 256
    macKmKeyValue: null
    macKa: HMacSHA1
    macKaKeySize: 256
    macKaKeyValue: null

  - ip: 239.9.9.9
    ciphersuite: blowfish/ECB/PKCS5Padding
    provider: BC
    keySize: 256
    keyValue: null
    macKm: HMacSHA1
    macKmKeySize: 256
    macKmKeyValue: null
    macKa: HMacSHA1
    macKaKeySize: 256
    macKaKeyValue: null
