configs:

  - ip: 224.10.10.10
    ciphersuite: blowfish/ECB/PKCS5Padding
    provider: BC
    keySize: 256
    keyValue: keyvalue
    mac: RC6-GMAC
    macKeySize: 256
    macKeyValue: mackeyvalue

  - ip: 224.10.10.11
    ciphersuite: blowfish/ECB/NoPadding
    provider: BC
    keySize: 512
    keyValue: keyvalue
    mac: RC6-GMAC
    macKeySize: 256
    macKeyValue: mackeyvalue

  - ip: 238.69.69.69
    ciphersuite: blowfish/ECB/PKCS5Padding
    provider: BC
    keySize: 256
    keyValue: keyvalue
    mac: RC6-GMAC
    macKeySize: 256
    macKeyValue: mackeyvalue
